config/routes.rb
Rails.application.routes.draw do

  scope "(:locale)" do
    get    '/login',   to: 'sessions#new'
    post   '/login',   to: 'sessions#create'
    delete '/logout',  to: 'sessions#destroy'
    resources :users
    resources :topics
    resources :labs
    resources :topic_labs do
      resources :ratings
    end
    
    root 'static_pages#show'
    get ':pages', to: 'static_pages#show', as: :pages
    get '*pages', to: 'static_pages#show'
    
    
  end

end

app/models/rating.rb
class Rating < ApplicationRecord
  
  def self.total_votes(topic_lab_id)
    self.where(topic_lab_id: topic_lab_id).count
  end

  def self.average_value(topic_lab_id)
    self.where(topic_lab_id: topic_lab_id).average(:value)
  end
    
end

app/controllers/ratings_controller.rb
class RatingsController < ApplicationController
  before_action :set_rating, only: [:show, :edit, :update, :destroy]
  before_action :admin_user, only: [:index, :destroy]

  # GET /ratings
  # GET /ratings.json
  def index
    @ratings = Rating.all
  end

  # GET /ratings/1
  # GET /ratings/1.json
  def show
  end

  # GET /ratings/new
  def new
    @rating = Rating.new
  end

  # GET /ratings/1/edit
  def edit
  end

  # POST /ratings
  # POST /ratings.json
  def create
    @rating = Rating.new(rating_params)
    @rating.topic_lab_id = params[:topic_lab_id]

    respond_to do |format|
      if @rating.save
        format.html { redirect_to topic_lab_path(@rating.topic_lab_id), notice: 'Rating was successfully created.' }
        format.json { render :show, status: :created, location: @rating }
      else
        format.html { redirect_to topic_lab_path(@rating.topic_lab_id), alert: 'Rating was not created.' }
        format.json { render json: @rating.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /ratings/1
  # PATCH/PUT /ratings/1.json
  def update
    respond_to do |format|
      if @rating.update(rating_params)
        format.html { redirect_to @rating, notice: 'Rating was successfully updated.' }
        format.json { render :show, status: :ok, location: @rating }
      else
        format.html { render :edit }
        format.json { render json: @rating.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /ratings/1
  # DELETE /ratings/1.json
  def destroy
    @rating.destroy
    respond_to do |format|
      format.html { redirect_to ratings_url, notice: 'Rating was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_rating
      @rating = Rating.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def rating_params
      params.require(:rating).permit(:value, :topic_lab_id)
    end
end

app/helpers/ratings_helper.rb
module RatingsHelper
end

app/views/ratings/_form.html.1.erb
<%= form_with(model: rating, local: true) do |form| %>
  <% if rating.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(rating.errors.count, "error") %> prohibited this rating from being saved:</h2>

      <ul>
      <% rating.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :value %>
    <%= form.text_field :value, id: :rating_value %>
  </div>

  <div class="field">
    <%= form.label :topic_lab_id %>
    <%= form.number_field :topic_lab_id, id: :rating_topic_lab_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/ratings/_form.html.erb
<%= form_for([@topic_lab, @rating]) do |f| %>
  <% if rating.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(rating.errors.count, "error") %> prohibited this rating from being saved:</h2>

      <ul>
      <% rating.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  
  <%= hidden_field_tag :topic_lab_id, @topic_lab.id %>

  low &nbsp;<%= f.radio_button :value, 1, :onclick => "this.form.submit();" %>&nbsp;
  <%= f.radio_button :value, 2, :onclick => "this.form.submit();" %>&nbsp;
  <%= f.radio_button :value, 3, :onclick => "this.form.submit();" %>&nbsp;
  <%= f.radio_button :value, 4, :onclick => "this.form.submit();" %>&nbsp;
  <%= f.radio_button :value, 5, :onclick => "this.form.submit();" %>&nbsp; high


<% end %>

app/views/ratings/edit.html.erb
<h1>Editing Rating</h1>

<%= render 'form', rating: @rating %>

<%= link_to 'Show', @rating %> |
<%= link_to 'Back', ratings_path %>

app/views/ratings/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Ratings</h1>

<table>
  <thead>
    <tr>
      <th>Value</th>
      <th>Topic lab</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @ratings.each do |rating| %>
      <tr>
        <td><%= rating.value %></td>
        <td><%= rating.topic_lab_id %></td>
        <td><%= link_to 'Show', rating %></td>
        <td><%= link_to 'Edit', edit_rating_path(rating) %></td>
        <td><%= link_to 'Destroy', rating, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Rating', new_topic_lab_rating_path %>

app/views/ratings/new.html.erb
<h1>New Rating</h1>

<%= render 'form', rating: @rating %>

<%= link_to 'Back', ratings_path %>

app/views/ratings/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Value:</strong>
  <%= @rating.value %>
</p>

<p>
  <strong>Topic lab:</strong>
  <%= @rating.topic_lab_id %>
</p>

<%= link_to 'Edit', edit_rating_path(@rating) %> |
<%= link_to 'Back', ratings_path %>