config/routes.rb
Rails.application.routes.draw do

  scope "(:locale)" do
    get    '/login',   to: 'sessions#new'
    post   '/login',   to: 'sessions#create'
    delete '/logout',  to: 'sessions#destroy'
    resources :users
    resources :topics
    resources :labs
    resources :topic_labs do
      resources :ratings
    end
    
    root 'static_pages#show'
    get ':pages', to: 'static_pages#show', as: :pages
    get '*pages', to: 'static_pages#show'
    
    
  end

end

app/models/topic_lab.rb
class TopicLab < ApplicationRecord
  
  belongs_to :topic
  belongs_to :lab
  has_many :rating
  
  private 
  
  def self.no_of_labs(topic_id)
    return self.where(topic_id: topic_id).count
  end  

  def self.next_topic_lab(topic_lab_id)
    topic_lab = self.find(topic_lab_id)
    next_lab = self.find_by(lab_order: topic_lab.lab_order + 1)
    
    if next_lab.nil? 
      return topic_lab
    else
      return next_lab
    end
  end

  def self.prev_topic_lab(topic_lab_id)
    topic_lab = self.find(topic_lab_id)
    prev_lab = self.find_by(lab_order: topic_lab.lab_order - 1)
    
    if prev_lab.nil? 
      return topic_lab
    else
      return prev_lab
    end
  end
  
end

app/controllers/topic_labs_controller.rb
class TopicLabsController < ApplicationController
  before_action :set_topic_lab, only: [:show, :edit, :update, :destroy]
  before_action :admin_user, except: [:show]

  # switch between static and db lab sheet
  @db_lab_sheet = true;

  # GET /topic_labs
  # GET /topic_labs.json
  def index
    @topic_labs = TopicLab.all
  end

  # GET /topic_labs/1
  # GET /topic_labs/1.json
  def show

    @topics = Topic.all.order(name: :asc)
    @prev_topic_lab = TopicLab.prev_topic_lab(@topic_lab.id)
    @next_topic_lab = TopicLab.next_topic_lab(@topic_lab.id)
    
    @rating = Rating.new
    @total_votes = Rating.total_votes(@topic_lab)
    @average_rating = Rating.average_value(@topic_lab)
    
    @progress = (@topic_lab.lab_order.to_f / TopicLab.no_of_labs(@topic_lab.topic_id)) * 100
 
  end

  # GET /topic_labs/new
  def new
    @topic_lab = TopicLab.new
  end

  # GET /topic_labs/1/edit
  def edit
  end

  # POST /topic_labs
  # POST /topic_labs.json
  def create
    @topic_lab = TopicLab.new(topic_lab_params)

    respond_to do |format|
      if @topic_lab.save
        format.html { redirect_to @topic_lab, success: 'Topic lab was successfully created.' }
        format.json { render :show, status: :created, location: @topic_lab }
      else
        format.html { render :new }
        format.json { render json: @topic_lab.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /topic_labs/1
  # PATCH/PUT /topic_labs/1.json
  def update
    respond_to do |format|
      if @topic_lab.update(topic_lab_params)
        format.html { redirect_to @topic_lab, success: 'Topic lab was successfully updated.' }
        format.json { render :show, status: :ok, location: @topic_lab }
      else
        format.html { render :edit }
        format.json { render json: @topic_lab.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /topic_labs/1
  # DELETE /topic_labs/1.json
  def destroy
    @topic_lab.destroy
    respond_to do |format|
      format.html { redirect_to topic_labs_url, success: 'Topic lab was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_topic_lab
      @topic_lab = TopicLab.find(params[:id])
      @lab_sheet = Lab.find(@topic_lab.lab_id).sheet
      
      @db_lab_sheet ?
        @lab_sheet = Lab.find(@topic_lab.lab_id).sheet : 
        @lab_sheet = "/labs/sheets/" + Topic.find(@topic_lab.topic_id).name.downcase + '/' + Lab.find(@topic_lab.lab_id).name
    
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def topic_lab_params
      params.require(:topic_lab).permit(:lab_order, :topic_id, :lab_id)
    end
end

app/helpers/topic_labs_helper.rb
module TopicLabsHelper
end

app/views/topic_labs/_form.html.erb
<%= form_with(model: topic_lab, local: true) do |form| %>
  <% if topic_lab.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(topic_lab.errors.count, "error") %> prohibited this topic_lab from being saved:</h2>

      <ul>
      <% topic_lab.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :lab_order %>
    <%= form.number_field :lab_order, id: :lab_order %>
  </div>
  
  <div class="field">
    <%= form.collection_select :topic_id, Topic.order(:name), :id, :name %>
  </div>

  <div class="field">
    <%= form.collection_select :lab_id, Lab.order(:name), :id, :name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/topic_labs/edit.html.erb
<h1>Editing Topic Lab</h1>

<%= render 'form', topic_lab: @topic_lab %>

<%= link_to 'Show', @topic_lab %> |
<%= link_to 'Back', topic_labs_path %>

app/views/topic_labs/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Topic Labs</h1>

<table>
  <thead>
    <tr>
      <th>Lab order</th>
      <th>Topic</th>
      <th>Lab</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @topic_labs.each do |topic_lab| %>
      <tr>
        <td><%= topic_lab.lab_order %></td>
        <td><%= topic_lab.topic_id %></td>
        <td><%= topic_lab.lab_id %></td>
        <td><%= link_to 'Show', topic_lab %></td>
        <td><%= link_to 'Edit', edit_topic_lab_path(topic_lab) %></td>
        <td><%= link_to 'Destroy', topic_lab, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Topic Lab', new_topic_lab_path %>

app/views/topic_labs/new.html.erb
<h1>New Topic Lab</h1>

<%= render 'form', topic_lab: @topic_lab %>

<%= link_to 'Back', topic_labs_path %>

app/views/topic_labs/show.html.erb
<% if @db_lab_sheet %> 
  <%= render inline: @lab_sheet   %>
<% else %>
  <%= render @lab_sheet   %>
<% end %>

<!-- %= render '/labs/sheets/rails_start_here.html.erb' % -->