config/routes.rb
Rails.application.routes.draw do

  scope "(:locale)" do
    get    '/login',   to: 'sessions#new'
    post   '/login',   to: 'sessions#create'
    delete '/logout',  to: 'sessions#destroy'
    resources :users
    resources :topics
    resources :labs
    resources :topic_labs do
      resources :ratings
    end
    
    root 'static_pages#show'
    get ':pages', to: 'static_pages#show', as: :pages
    get '*pages', to: 'static_pages#show'
    
    
  end

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="<%= I18n.locale %>">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title><%= content_for?(:title) ? yield(:title) : "chubkins" %></title>
    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "application", 'data-turbolinks-track' => true %>
    <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/foundicons/3.0.0/foundation-icons.min.css"/>
    <link href="https://fonts.googleapis.com/css?family=Delius" rel="stylesheet" />
    <%= csrf_meta_tags %>
  </head>

  <body dir="<%= @local_dir %>">
<!--
    <div class="grid-x grid-padding-x">
      <div class="cell" data-sticky-container>
        <div id="top-bar" class="sticky top-bar" data-sticky data-margin-top="0">
          <div class="top-bar-left">
            <nav>
              <ul class="menu">
                <li>
                  <%= link_to ('<i class="fi-home"></i> ').html_safe + t('chubkins'), root_path, data: { turbolinks: "false" } %>
                </li>
                <li><%= link_to image_tag("gb.svg", alt: "en", class: 'flag-icon') +  t('en'), root_path(locale: 'en'), data: { turbolinks: "false" } %></li>
                <li><%= link_to image_tag("np.svg", alt: "np", class: 'flag-icon') + t('ne'), root_path(locale: 'ne'), data: { turbolinks: "false" } %></li>
                <li><%= link_to image_tag("ir.svg", alt: "ir", class: 'flag-icon') + t('fa'), root_path(locale: 'fa'), data: { turbolinks: "false" } %></li>
                <li><%= link_to image_tag("th.svg", alt: "th", class: 'flag-icon') + t('th'), root_path(locale: 'th'), data: { turbolinks: "false" } %></li>
              </ul>
            </nav>
          </div>
          <div class="top-bar-right">
            <ul class="menu">
              <% if logged_in? %>
                <% if logged_in_ebbi? %>
                  <li><%= link_to "Labs", labs_path %></li>
                  <li><%= link_to "Topics", topics_path %></li>
                  <li><%= link_to "Topic Labs", topic_labs_path %></li>
                  <li><%= link_to "Users", users_path %></li>
                <% end %>                  
                <li><%= link_to current_user.name, user_path(current_user) %></li>
                <li><%= link_to "Log out", logout_path, method: :delete %></li>
              <% else %>
                <li><%= link_to "Log in", login_path %></li>
              <% end %> 
            </ul>
          </div>
        </div>
      </div>
    </div>
-->


    
        <%= yield %>
        


  </body>
</html>